-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT,
  description TEXT,
  avatar_url TEXT,
  mbti TEXT,
  zodiac TEXT,
  location TEXT,
  tags TEXT[] DEFAULT '{}',
  match_score INTEGER DEFAULT 0,
  likes_count INTEGER DEFAULT 0,
  followers_count INTEGER DEFAULT 0,
  role TEXT DEFAULT 'user' NOT NULL, -- 'user' or 'admin'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create links table
CREATE TABLE IF NOT EXISTS public.links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  icon TEXT,
  clicks INTEGER DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.links ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Public links are viewable by everyone" ON public.links
  FOR SELECT USING (true);

-- Authenticated user access
CREATE POLICY "Users can insert their own profile" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can manage own links" ON public.links
  FOR ALL USING (profile_id IN (
    SELECT id FROM public.profiles WHERE auth.uid() = id
  ));

-- RPC Function for incrementing likes
CREATE OR REPLACE FUNCTION increment_likes(profile_user_id UUID)
RETURNS void AS $$
BEGIN
  UPDATE public.profiles
  SET likes_count = likes_count + 1
  WHERE id = profile_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
